[binaries]
c = 'aarch64-linux-gnu-gcc'
cpp = 'aarch64-linux-gnu-g++'
ar = 'aarch64-linux-gnu-ar'
nm = 'aarch64-linux-gnu-nm'
ranlib = 'aarch64-linux-gnu-ranlib'
strip = 'aarch64-linux-gnu-strip'
pkgconfig = 'aarch64-linux-gnu-pkg-config'
exe_wrapper = ['qemu-aarch64', '-L', '/usr/aarch64-linux-gnu']

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'armv8a'
endian = 'little'

[properties]
sys_root = '/usr/aarch64-linux-gnu'
pkg_config_libdir = '/usr/aarch64-linux-gnu/lib/pkgconfig'
